#!/usr/bin/env bash
# container fix
pkill -f apache2
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
