#!/usr/bin/env bash
# install nginx, set up 404
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo sh -c 'echo "Ceci n'est pas une page" > /usr/share/nginx/html/err_404.html'
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.zombo.com permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a error_page 404 /err_404.html;\nlocation = /err_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx restart
