#!/usr/bin/env bash
# Manages the "my_process" file

FILE="/var/run/my_process.pid"
PID=$(cat "$FILE" 2>/dev/null)
#echo "$PID"
command="$1"
case "$command" in
	"start")
		./manage_my_process& 2>/dev/null
		PID="$!"
		echo "$PID" > "$FILE"
		echo "manage_my_process started"
		;;
	"stop")
		kill "$PID"
		rm -f "$FILE"
		echo "manage_my_process stopped"
		;;
	"restart")
		kill "$PID" 2>/dev/null
		rm -f "$FILE"
		./manage_my_process& 2>/dev/null
		PID="$!"
		echo "$PID" > "$FILE"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
