#!/usr/bin/env bash
# Displays 1-2, with different text on 4th and 9th and 17th iteration
i=1

while [ $i -lt 21 ]
do
	echo $i
	case $i in
	
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	*)
		;;
	esac
	i=$(( i+1))
done
