#!/usr/bin/env bash
# install haproxy.
sudo apt-get -y update
sudo apt-get install -y haproxy

sudo echo "
defaults
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    log global
    mode http
frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    option forwardfor
    server 3248-web-01 35.243.191.222:80 check
    server 3248-web-02 34.138.215.176:80 check
listen stats
    bind :32700
    stats enable
    stats uri /" >> /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
